project:
  type: book
  output-dir: _book

language:
  title-block-author-single: "Edited by"
  title-block-author-plural: "Edited by"

book:
  title: "Handbook of Cognitive Science of Climate Change"
  author: "Magdalena Sabat"
  date: today
  search: true
  page-navigation: true
  downloads: [pdf, epub]

  page-footer:
    left: "© 2026 Magdalena Sabat"
    right:
      - icon: github
        href: https://github.com/magdalenasabat/your-repo

  chapters:
    - contributors.qmd
    - index.qmd

    - part: "Introduction"
      chapters:
        - chapters/intro.qmd

    - part: "Chapters"
      chapters:
        - chapters/ch01-chapter-one.qmd
        - chapters/ch01-resources.qmd
        - chapters/ch02-chapter-two.qmd
        - chapters/ch03-chapter-three.qmd

    - references.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    number-sections: true

  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    number-sections: true
    colorlinks: true
    mainfont: "Open Sans"       # ← body text
    sansfont: "Open Sans"       # ← headings (KOMA uses sans-serif for those)

  epub:
    toc: true
    number-sections: true

bibliography: references.bib